version: '3'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD:
      MYSQL_USER: laravel
    user: 1000:1000
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
